### ISSUE TITLE
RSpec + Pundit; Undefined method all? and none?

### ISSUE THREAD

**Issue by tkeifer** [varvet/pundit#130]
This may be something really simple, but I was unable to find any answer after extensive googling. 

I'm trying to run the following RSpec test:

```
require "spec_helper"

describe ReportPolicy do
  subject { ReportPolicy.new(user, report) }

  let(:user)    { FactoryGirl.create(:user) }
  let(:report)  { FactoryGirl.create(:report, organization_id: user.organization_id) }

  context "for a user" do
    it { should       permit(:show) }
    it { should_not   permit(:edit) }
  end  
end
```

It is failing with the errors:

```
1) ReportPolicy for a user should permit :show
     Failure/Error: it { should       permit(:show) }
     NoMethodError:
       undefined method `all?' for nil:NilClass
     # ./spec/policies/report_policy_spec.rb:10:in `block (3 levels) in <top (required)>'
2) ReportPolicy for a user should not permit :edit
     Failure/Error: it { should_not   permit(:edit) }
     NoMethodError:
       undefined method `none?' for nil:NilClass
     # ./spec/policies/report_policy_spec.rb:11:in `block (3 levels) in <top (required)>'
```

Can anyone explain what is going on here?

**Comment by ColinW520** [comment]
thanks for this thread - just saved me a ton of time

**Comment by tirdadc** [comment]
I wish I had found this before I ended up renaming the custom matcher to fix the issue. Thanks for the `policy_scope` spec example!

**Comment by chickenfingers** [comment]
failure_message_for_should and failure_message_for_should_not are deprecated. Use failure_message and failure_message_when_negated instead.
