### ISSUE TITLE
Scopes get cached and are resolved during Rails error handling

### ISSUE THREAD

**Issue by al** [varvet/pundit#510]
I've noticed something Rails specific with the behaviour of `#policy_scope` when your app errors. It's really only a problem if you have _big_ tables, but I though it might be worth sharing in case anyone else finds their app running unexpected queries during error handling.

`#policy_scope` causes the Scopes to be cached internally by Pundit. If your app subsequently encounters an error, these cached Scopes appear to get inspected by something in the Rails error handling process (both production and development environments). That causes the Scope queries to be executed.

Typically that won't be a problem, but if they happen to resolve to a very large set of records or an otherwise expensive query, you may find yourself looking at an unresponsive server and wondering where the hell this `SELECT * FROM giant_table` in your logs is coming from.

I believe Rails 5.1 won't suffer as it tacks on a `limit` to the queries, but on older versions the behaviour can be very frustrating.

It can be avoided by constructing the Scopes directly and bypassing `#policy_scope` caching.

```ruby
class ThingPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end

  def show?
    true
  end
end
```

```ruby
class ThingsController < ApplicationController
  def show
    # With caching ... will cause `SELECT  "things".* FROM "things"` to be executed when an error occurs
    @thing = policy_scope(Thing).find(params[:id])

    # Without caching
    # @thing = ThingPolicy::Scope.new(pundit_user, Thing).resolve.find(params[:id])

    authorize @thing

    this_line_will_cause_a_name_error
  end
end
```

Just thought I'd mention it ...

**Comment by Linuus** [comment]
Hmmm odd.

I just generated a Rails 5.2 app with a Thing scaffold and got these results with your code above:

Using `policy_scope(Thing).find(params[:id])`
```
Started GET "/things/1" for 127.0.0.1 at 2018-04-30 19:25:07 +0200
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Processing by ThingsController#show as HTML
  Parameters: {"id"=>"1"}
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/things_controller.rb:14
  Thing Load (0.2ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Completed 500 Internal Server Error in 188ms (ActiveRecord: 0.6ms)



  Thing Load (0.2ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
NameError (undefined local variable or method `this_line_will_cause_a_name_error' for #<ThingsController:0x00007fb7bee47d20>):

app/controllers/things_controller.rb:21:in `show'
```

Using `ThingPolicy::Scope.new(pundit_user, Thing).resolve.find(params[:id])`
```
Started GET "/things/1" for 127.0.0.1 at 2018-04-30 19:25:26 +0200
   (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Processing by ThingsController#show as HTML
  Parameters: {"id"=>"1"}
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/things_controller.rb:17
Completed 500 Internal Server Error in 175ms (ActiveRecord: 0.7ms)



NameError (undefined local variable or method `this_line_will_cause_a_name_error' for #<ThingsController:0x00007fc5d047c3c0>):

app/controllers/things_controller.rb:21:in `show'
```

I'm not sure why this would happen.

Also, it only happens when you have `scope.all` not if you return only `scope`.

**Comment by Linuus** [comment]
This doesn't seem to be an issue with Pundit.

Try using this controller method instead:

```ruby
  def show
    @things = Thing.all

    @thing = @things.find(params[:id])

    this_line_will_cause_a_name_error
  end
```

This produces this log output:
```
Started GET "/things/1" for 127.0.0.1 at 2018-04-30 20:05:49 +0200
   (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Processing by ThingsController#show as HTML
  Parameters: {"id"=>"1"}
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/things_controller.rb:15
  Thing Load (0.2ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Completed 500 Internal Server Error in 189ms (ActiveRecord: 0.6ms)



  Thing Load (0.2ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
NameError (undefined local variable or method `this_line_will_cause_a_name_error' for #<ThingsController:0x00007fac97de2380>):

app/controllers/things_controller.rb:17:in `show'
```

This seems to be a problem with Rails/ActiveRecord/Something, or am I missing something?

I'll close this issue, please re-open it if you disagree :)

**Comment by Linuus** [comment]
For completeness, I've opened an issue on the Rails issue tracker for this: https://github.com/rails/rails/issues/32810
